const mongoose = require('mongoose')

const trainSchema = new mongoose.Schema({
    _id: String,
    trustID: String,
    descr: String,
    lastMovement: {
        event_type: String,
        gbtt_timestamp: String,
        original_loc_stanox: String,
        planned_timestamp: String,
        timetable_variation: Number,
        original_loc_timestamp: String,
        current_train_id: String,
        delay_monitoring_point: Boolean,
        next_report_run_time: String,
        reporting_stanox: String,
        actual_timestamp: String,
        correction_ind: Boolean,
        event_source: String,
        train_file_address: String,
        platform: Number,
        division_code: String,
        train_terminated: Boolean,
        train_id: String,
        offroute_ind: Boolean,
        variation_status: String,
        train_service_code: String,
        toc_id: String,
        loc_stanox: String,
        auto_expected: String,
        direction_ind: String,
        route: String,
        planned_event_type: String,
        next_report_stanox: String,
        line_ind: String
    },
    lastUpdate: String,
    movementActive: Boolean,
    movementActivation: {
        schedule_source: String,
        train_file_address: String,
        schedule_end_date: String,
        train_id: String,
        tp_origin_timestamp: String,
        creation_timestamp: String,
        tp_origin_stanox: String,
        origin_dep_timestamp: String,
        train_service_code: String,
        toc_id: String,
        d1266_record_number: String,
        train_call_type: String,
        train_uid: String,
        train_call_mode: String,
        schedule_type: String,
        sched_origin_stanox: String,
        schedule_wtt_id: String,
        schedule_start_date: String,
    },
    schedule: {
        _id: String,
        IF_bank_holiday_running: String,
        CIF_stp_indicator: String,
        CIF_train_uid: String,
        applicable_timetable: String,
        atoc_code: String,
        new_schedule_segment: {
            traction_class: String,
            uic_code: String,
        },
        schedule_days_runs: String,
        schedule_end_date: String,
        schedule_segment: {
            signalling_id: String,
            CIF_train_category: String,
            CIF_headcode: String,
            CIF_course_indicator: Number,
            CIF_train_service_code: String,
            CIF_business_sector: String,
            CIF_power_type: String,
            CIF_timing_load: String,
            CIF_speed: String,
            CIF_operating_characteristics: String,
            IF_train_class: String,
            CIF_sleepers: String,
            CIF_reservations: String,
            CIF_connection_indicator: String,
            CIF_catering_code: String,
            CIF_service_branding: String,
            schedule_location: {},
        },
        schedule_start_date: String,
        train_status: String,
    },
    scheduleActive: Boolean,
    trustActivated: Boolean,
    coo: {}
})

const Train = mongoose.model('Train', trainSchema)
module.exports = Train;