const mongoose = require('mongoose')

const trainSchema = new mongoose.Schema({
    _id: string,
    trustID: string,
    descr: string,
    lastMovement: {
        event_type: string,
        gbtt_timestamp: string,
        original_loc_stanox: string,
        planned_timestamp: string,
        timetable_variation: number,
        original_loc_timestamp: string,
        current_train_id: string,
        delay_monitoring_point: boolean,
        next_report_run_time: string,
        reporting_stanox: string,
        actual_timestamp: string,
        correction_ind: boolean,
        event_source: string,
        train_file_address: string,
        platform: number,
        division_code: string,
        train_terminated: boolean,
        train_id: string,
        offroute_ind: boolean,
        variation_status: string,
        train_service_code: string,
        toc_id: string,
        loc_stanox: string,
        auto_expected: string,
        direction_ind: string,
        route: string,
        planned_event_type: string,
        next_report_stanox: string,
        line_ind: string
    },
    lastUpdate: string,
    movementActive: boolean,
    movementActivation: {
        schedule_source: string,
        train_file_address: string,
        schedule_end_date: string,
        train_id: string,
        tp_origin_timestamp: string,
        creation_timestamp: string,
        tp_origin_stanox: string,
        origin_dep_timestamp: string,
        train_service_code: string,
        toc_id: string,
        d1266_record_number: string,
        train_call_type: string,
        train_uid: string,
        train_call_mode: string,
        schedule_type: string,
        sched_origin_stanox: string,
        schedule_wtt_id: string,
        schedule_start_date: string,
    },
    schedule: {
        _id: string,
        IF_bank_holiday_running: string,
        CIF_stp_indicator: string,
        CIF_train_uid: string,
        applicable_timetable: string,
        atoc_code: string,
        new_schedule_segment: {
            traction_class: string,
            uic_code: string,
        },
        schedule_days_runs: string,
        schedule_end_date: string,
        schedule_segment: {
            signalling_id: string,
            CIF_train_category: string,
            CIF_headcode: string,
            CIF_course_indicator: number,
            CIF_train_service_code: string,
            CIF_business_sector: string,
            CIF_power_type: string,
            CIF_timing_load: string,
            CIF_speed: string,
            CIF_operating_characteristics: string,
            IF_train_class: string,
            CIF_sleepers: string,
            CIF_reservations: string,
            CIF_connection_indicator: string,
            CIF_catering_code: string,
            CIF_service_branding: string,
            schedule_location: {},
        },
        schedule_start_date: string,
        train_status: string,
    },
    scheduleActive: boolean,
    trustActivated: boolean,
    coo: object
})

const Train = mongoose.model('Train', trainSchema)
module.exports = Train;